name: thepause_audio_player_app
description: "A Flutter-based audio player app that allows users to play audio files seamlessly, including support for background playback. The app should be lightweight, user-friendly, and optimized for both Android and iOS platforms."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  flutter_clean_architecture: ^6.0.1
  mockito: ^5.4.4
  shared_preferences:
  bloc:
  flutter_bloc:
  equatable:
  google_fonts:
  flutter_svg:
  sqflite:
  path_provider:
  path:
  permission_handler:
  just_audio:
  on_audio_query:
  layout_pro:
  shimmer_effect:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/svgs/
    - assets/icons/