name: thepause_audio_player_app
description: "A Flutter-based audio player app that allows users to play audio files seamlessly, including support for background playback. The app should be lightweight, user-friendly, and optimized for both Android and iOS platforms."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  flutter_clean_architecture: ^6.0.1
  mockito: ^5.4.4
  bloc: ^9.0.0
  equatable: ^2.0.5  
  flutter_bloc: ^9.0.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  just_audio: ^0.9.41
  layout_pro: ^0.0.4
  on_audio_query: ^2.9.0
  path: ^1.9.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  shimmer_effect: ^1.0.4
  sqflite: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/svgs/
    - assets/icons/